### ISSUE TITLE
A couple of ideas

### ISSUE THREAD

**Issue by AlexanderMalashchenko** [simon-winter/UnityDotsAuthoringGenerator#2]
Possibility to save the authoring to the current file without constantly specifying the full path.

Hotkey for those who are not comfortable calling the generation through the solution.

To be honest, I don't really understand the idea of ​​snippets when it's very cool done natively in Visual Studio. Perhaps it is worth going along the path of expanding similar use cases to get rid of the boilerprint (just steal everything done in rider lol) and not duplicate the existing functionality?

Anyway thanks for your work, very helpful.

**Comment by simon-winter** [comment]
Hi Alexander,
Thanks for your feedback!

1) the authoring is generated nexto the right clicked file, if the path in settings is set to an empty string.
   I will add a checkbox for that instead in the next release to make this behavior more clear
   
2) i will add hotkeys for the todo aswell, maybe i can even hook into the on document saved event

3) snippets were born, because i was always forgetting the entityCommandBuffer syntax to generate it. so i wanted to have simple snippets, but i'm happy to improve this. sadly i am not aware of the native VS version of snippets nor do i know what rider has to offer, as i don't have a licence. If you can provide me an explanation of how rider does it, or which usecase you envision, i can see if i can implement it.

Sadly visual studio extensions are not so well documented, so bear with me if i need a few days to find the time ;)

**Comment by simon-winter** [comment]
Guess i'll have a look here: https://blog.jetbrains.com/dotnet/2023/03/16/unity-dots-support-in-rider-2023-1/
and see which ideas i can use

**Comment by simon-winter** [comment]
I have just released a new version which addresses your suggestions.

Shortcuts can be set via the normal Visual Studio shortcut manager, see the readme on the main page on the bottom, i added an explanation. If everything worked out "ALT+G" should be set as default shortcut to generate the authoring.

some other improvements included aswell
